#!/usr/bin/env bash

export USER=root
source $HOME/.nix-profile/etc/profile.d/nix.sh

CRONIC=/bootstrap.sh/scripts/cronic
DUPLY=/bootstrap.sh/scripts/duply.nix.sh

${CRONIC} ${DUPLY} awsS3 backup
${CRONIC} ${DUPLY} awsS3 purgeIncr_purgeFull_purge --force
