#!/usr/bin/env bash

# iptables  -D FORWARD -i tun0 -j ACCEPT
# ip6tables -D FORWARD -i tun0 -j ACCEPT

iptables  -t nat -D POSTROUTING -s 172.23.223.0/24           -o ens3 -j MASQUERADE
ip6tables -t nat -D POSTROUTING -s fd9b:48d9:b3fd:8081::/64  -o ens3 -j MASQUERADE



IPV4=$(hostname -I | tr ' ' '\n' | egrep '^[0-9.]+$'       | egrep -v '^(127|10|192\.168|172\.23)\.')
IPV6=$(hostname -I | tr ' ' '\n' | egrep '^[0-9a-fA-F:]+$' | egrep -v '^(:|f[c-f])')

iptables  -t nat -D PREROUTING -d $IPV4 -p tcp -m multiport ! --dports 22,443 -j DNAT --to-destination :443
ip6tables -t nat -D PREROUTING -d $IPV6 -p tcp -m multiport ! --dports 22,443 -j DNAT --to-destination :443
