#!/usr/bin/env bash

while IFS= read -r -d '' cert; do
    /bootstrap.sh/externals/haproxy-ocsp-stapling-updater/hapos-upd --cert "${cert}" --VAfile -
done < <(find /etc/haproxy/ssl \( -name '*.pem' -or -name '*.pem.rsa' -or -name '*.pem.ecdsa' \) ! -name 'dh-4096.pem' -print0)
