#!/usr/bin/env bash

while IFS= read -r -d '' certdir; do
    cat "/etc/letsencrypt/live/${certdir}/fullchain.pem" "/etc/letsencrypt/live/${certdir}/privkey.pem" | tee "/etc/haproxy/ssl/${certdir}.pem" > /dev/null
    rm -f "/etc/haproxy/ssl/${certdir}.pem.issuer"
    rm -f "/etc/haproxy/ssl/${certdir}.pem.ocsp"
    /bootstrap.sh/externals/haproxy-ocsp-stapling-updater/hapos-upd --cert "/etc/haproxy/ssl/${certdir}.pem" --VAfile -
done < <(find /etc/letsencrypt/live -mindepth 1 -maxdepth 1 -type d -printf '%f\0')

service haproxy reload
