#!/usr/bin/env bash

while IFS= read -r -d '' certdir; do

    cat "/etc/ssl/letsencrypt/${certdir}/rsa-fullchain.pem" "/etc/ssl/letsencrypt/${certdir}/rsa-key.pem" | tee "/etc/haproxy/ssl/${certdir}.pem.rsa" > /dev/null
    chmod 600 "/etc/haproxy/ssl/${certdir}.pem.rsa"
    rm -f "/etc/haproxy/ssl/${certdir}.pem.rsa.issuer"
    rm -f "/etc/haproxy/ssl/${certdir}.pem.rsa.ocsp"
    /bootstrap.sh/externals/haproxy-ocsp-stapling-updater/hapos-upd --cert "/etc/haproxy/ssl/${certdir}.pem.rsa" --VAfile -

done < <(find /etc/ssl/letsencrypt -mindepth 1 -maxdepth 1 -type d -printf '%f\0')

service haproxy reload
