#!/usr/bin/env bash

export DO_API_KEY="..."
# wird in /root/.acme.sh/config/account.conf abgespeichert!


acme.sh \
    --issue \
    --dns dns_dgon_quyo \
    \
    -d mx.quyo.net \
    -d mx.fra1.do.quyo.net \
    \
    --accountkeylength 4096 \
    --keylength 4096 \
    --days 30 \
    \
    --cert-file      /etc/ssl/letsencrypt/mx.quyo.net/rsa-cert.pem  \
    --key-file       /etc/ssl/letsencrypt/mx.quyo.net/rsa-key.pem  \
    --ca-file        /etc/ssl/letsencrypt/mx.quyo.net/rsa-chain.pem \
    --fullchain-file /etc/ssl/letsencrypt/mx.quyo.net/rsa-fullchain.pem \
    --reloadcmd "service postfix reload ; service dovecot reload"


acme.sh \
    --issue \
    --dns dns_dgon_quyo \
    \
    -d mx.quyo.net \
    -d mx.fra1.do.quyo.net \
    \
    --accountkeylength 4096 \
    --keylength ec-256 \
    --days 30 \
    \
    --cert-file      /etc/ssl/letsencrypt/mx.quyo.net/ec-cert.pem  \
    --key-file       /etc/ssl/letsencrypt/mx.quyo.net/ec-key.pem  \
    --ca-file        /etc/ssl/letsencrypt/mx.quyo.net/ec-chain.pem \
    --fullchain-file /etc/ssl/letsencrypt/mx.quyo.net/ec-fullchain.pem \
    --reloadcmd "service postfix reload ; service dovecot reload"


#   \
#   --pre-hook "echo this is pre hook that happens before attempting to issue a certificate."  \
#   --post-hook "echo this is post hook that happens after attempting to issue a certificate."  \
#   --renew-hook "echo this will be called when certs are successfully renewed." \
#   --reloadcmd "echo this runs after successfully installing certificates."
