#!/usr/bin/env bash

export ACMEDNS_UPDATE_URL="https://api.ca.quyo.net/update"
export ACMEDNS_USERNAME="<username>"
export ACMEDNS_PASSWORD="<password>"
export ACMEDNS_SUBDOMAIN="<subdomain>"


DOMAIN=quyo.net

mkdir -p "/etc/ssl/letsencrypt/$DOMAIN"

chown root:ssl-cert "/etc/ssl/letsencrypt"
chown root:ssl-cert "/etc/ssl/letsencrypt/$DOMAIN"

chmod 750 "/etc/ssl/letsencrypt"
chmod 750 "/etc/ssl/letsencrypt/$DOMAIN"


RELOADCMD=haproxy-rsa

acme.sh \
    --issue \
    --dns dns_acmedns \
    --domain-alias ${ACMEDNS_SUBDOMAIN}.acme-challenge.ca.quyo.net \
    \
    -d ${DOMAIN} \
    -d www.${DOMAIN} \
    \
    --accountkeylength 4096 \
    --keylength 4096 \
    --ocsp-must-staple \
    --days 30 \
    \
    --cert-file      "/etc/ssl/letsencrypt/$DOMAIN/rsa-cert.pem"  \
    --key-file       "/etc/ssl/letsencrypt/$DOMAIN/rsa-key.pem"  \
    --ca-file        "/etc/ssl/letsencrypt/$DOMAIN/rsa-chain.pem" \
    --fullchain-file "/etc/ssl/letsencrypt/$DOMAIN/rsa-fullchain.pem" \
    --reloadcmd "$HOME/.acme.sh/hooks/reloadcmd/$RELOADCMD"


RELOADCMD=haproxy-ec

acme.sh \
    --issue \
    --dns dns_acmedns \
    --domain-alias ${ACMEDNS_SUBDOMAIN}.acme-challenge.ca.quyo.net \
    \
    -d ${DOMAIN} \
    -d www.${DOMAIN} \
    \
    --accountkeylength 4096 \
    --keylength ec-384 \
    --ocsp-must-staple \
    --days 30 \
    \
    --cert-file      "/etc/ssl/letsencrypt/$DOMAIN/ec-cert.pem"  \
    --key-file       "/etc/ssl/letsencrypt/$DOMAIN/ec-key.pem"  \
    --ca-file        "/etc/ssl/letsencrypt/$DOMAIN/ec-chain.pem" \
    --fullchain-file "/etc/ssl/letsencrypt/$DOMAIN/ec-fullchain.pem" \
    --reloadcmd "$HOME/.acme.sh/hooks/reloadcmd/$RELOADCMD"
