#!/usr/bin/env sh

acme.sh \
    --issue \
    --standalone \
    --httpport 80 \
    \
    -d mx.fra1.do.quyo.net \
    -d mx.quyo.net \
    \
    --accountkeylength 4096 \
    --keylength ec-256 \
    --days 30 \
    \
    --cert-file      /etc/ssl/mx.fra1.do.quyo.net/ec-cert.pem  \
    --key-file       /etc/ssl/mx.fra1.do.quyo.net/ec-key.pem  \
    --ca-file        /etc/ssl/mx.fra1.do.quyo.net/ec-chain.pem \
    --fullchain-file /etc/ssl/mx.fra1.do.quyo.net/ec-fullchain.pem \
    --reloadcmd "service postfix reload ; service dovecot reload"
#   \
#   --pre-hook "echo this is pre hook that happens before attempting to issue a certificate."  \
#   --post-hook "echo this is post hook that happens after attempting to issue a certificate."  \
#   --renew-hook "echo this will be called when certs are successfully renewed." \
#   --reloadcmd "echo this runs after successfully installing certificates."
