#!/usr/bin/env sh

apt install -y update-manager-core
apt install -y openssh-client openssh-server openssh-sftp-server
apt install -y wget curl
apt install -y screen tmux dtach
apt install -y vim joe nano
apt install -y git
apt install -y mc
apt install -y chrony
apt install -y htop iotop iftop traceroute
DEBIAN_FRONTEND=noninteractive apt install -y postfix logcheck
apt install -y cron-apt
apt install -y monit
# apt install -y logwatch libsys-cpu-perl libsys-meminfo-perl
apt install -y fail2ban whois python3-pyinotify
