#!/usr/bin/env sh

set -e

apt install dnsdist

echo 'nameserver 127.0.0.1' > /etc/resolv.conf

ln -sf /bootstrap.sh/rootfs/etc/unbound/unbound.conf.d/quyo-public-resolver.conf.d      /etc/unbound/unbound.conf.d/
ln -sf /bootstrap.sh/rootfs/etc/unbound/unbound.conf.d/zzz-quyo-public-resolver.conf    /etc/unbound/unbound.conf.d/
ln -sf /bootstrap.sh/rootfs/etc/unbound/unbound.conf.d/zzz-quyo-dnsdist-listen.conf     /etc/unbound/unbound.conf.d/

ln -sf /bootstrap.sh/rootfs/etc/dnsdist/dnsdist.conf                                    /etc/dnsdist/
