#!/usr/bin/env sh

#
# link config files
#

mv ~/.joerc ~/.joerc~

ln -s /bootstrap.sh/homefs/.joerc           ~/.joerc
ln -s /bootstrap.sh/homefs/.joe             ~/.joe
ln -s /bootstrap.sh/homefs/.selected_editor ~/.selected_editor
