#!/usr/bin/env sh

#
# link config files
#

rm -rf ~/.joe/

ln -sf /bootstrap.sh/homefs/.joerc            --target-directory=~/
ln -sf /bootstrap.sh/homefs/.joe/             --target-directory=~/
ln -sf /bootstrap.sh/homefs/.selected_editor  --target-directory=~/
