#!/usr/bin/env sh

#
# link config files
#

ln -sf /bootstrap.sh/homefs/.joerc           ~/.joerc
ln -sf /bootstrap.sh/homefs/.joe             ~/.joe
ln -sf /bootstrap.sh/homefs/.selected_editor ~/.selected_editor
