#!/usr/bin/env sh

#
# link files
#

ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/amavisd-new       --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/bind              --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/chron             --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/chrony            --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/cron-apt          --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/dovecot           --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/kernel            --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/postfix           --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/postfwd           --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/postgrey          --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/spamc             --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/spamd             --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/ssh               --target-directory=/etc/logcheck/ignore.d.server/
ln -sf /bootstrap.sh/rootfs/etc/logcheck/ignore.d.server/systemd           --target-directory=/etc/logcheck/ignore.d.server/
