#!/usr/bin/env sh

#
# link files
#

rm -rf /etc/monit/conf-available/
rm -rf /etc/monit/conf-enabled/
rm -rf /etc/monit/templates/

ln -sf /bootstrap.sh/rootfs/etc/monit/monitrc          --target-directory=/etc/monit/
ln -sf /bootstrap.sh/rootfs/etc/monit/conf-available/  --target-directory=/etc/monit/
ln -sf /bootstrap.sh/rootfs/etc/monit/conf-enabled/    --target-directory=/etc/monit/
ln -sf /bootstrap.sh/rootfs/etc/monit/templates/       --target-directory=/etc/monit/

chmod 600 /etc/monit/monitrc
