#!/usr/bin/env sh

#
# link files
#

ln -sf /bootstrap.sh/rootfs/etc/monit/monitrc         /etc/monit/monitrc
ln -sf /bootstrap.sh/rootfs/etc/monit/conf-available  /etc/monit/conf-available
ln -sf /bootstrap.sh/rootfs/etc/monit/conf-enabled    /etc/monit/conf-enabled
ln -sf /bootstrap.sh/rootfs/etc/monit/templates       /etc/monit/templates
