#!/usr/bin/env sh

#
# link config files
#

ln -sf /bootstrap.sh/rootfs/etc/ssh/ssh_config  /etc/ssh/ssh_config
ln -sf /bootstrap.sh/rootfs/etc/ssh/sshd_config /etc/ssh/sshd_config



#
# generate host keys
#

rm -f /etc/ssh/ssh_host_dsa_key     /etc/ssh/ssh_host_dsa_key.pub
rm -f /etc/ssh/ssh_host_ecdsa_key   /etc/ssh/ssh_host_ecdsa_key.pub
rm -f /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key.pub
rm -f /etc/ssh/ssh_host_rsa_key     /etc/ssh/ssh_host_rsa_key.pub

mkdir /etc/ssh/keys

ssh-keygen -N '' -t rsa     -b 4096 -f /etc/ssh/keys/ssh_host_key_rsa
ssh-keygen -N '' -t ecdsa   -b 384  -f /etc/ssh/keys/ssh_host_key_ecdsa
ssh-keygen -N '' -t ed25519         -f /etc/ssh/keys/ssh_host_key_ed25519



#
# generate user keys
#

ssh-keygen -N '' -t rsa     -b 4096 -f ~/.ssh/id_rsa
ssh-keygen -N '' -t ecdsa   -b 384  -f ~/.ssh/id_ecdsa
ssh-keygen -N '' -t ed25519         -f ~/.ssh/id_ed25519



#
# download moduli from https://2ton.com.au/dhtool/
#

curl https://2ton.com.au/dhparam/2048/ssh  > /etc/ssh/moduli
curl https://2ton.com.au/dhparam/3072/ssh >> /etc/ssh/moduli
curl https://2ton.com.au/dhparam/4096/ssh >> /etc/ssh/moduli
curl https://2ton.com.au/dhparam/8192/ssh >> /etc/ssh/moduli



#
# run dhtool from https://2ton.com.au/HeavyThing-1.16.tar.gz
#

wget https://2ton.com.au/HeavyThing-1.16.tar.gz
tar xzf HeavyThing-1.16.tar.gz
cp HeavyThing-1.16/dhtool/dhtool /usr/local/bin

### run later: dhtool /etc/ssh/moduli | tee /etc/ssh/moduli.dhtool



#
# link authorized_keys
#

ln -sf /bootstrap.sh/homefs/.ssh/authorized_keys ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
