#!/usr/bin/env sh

sed --in-place 's/^inet_interfaces = all$/inet_interfaces = loopback-only/' /etc/postfix/main.cf

ln -sf /bootstrap.sh/rootfs/etc/aliases --target-directory=/etc/
newaliases

service postfix restart
