#!/usr/bin/env bash

set -e

cd /root/tmp

apt remove --purge librsync-dev
apt install python-lockfile

wget -O librsync1_0.9.7-10build1_amd64.deb http://de.archive.ubuntu.com/ubuntu/pool/main/libr/librsync/librsync1_0.9.7-10build1_amd64.deb
dpkg -i librsync1_0.9.7-10build1_amd64.deb
rm      librsync1_0.9.7-10build1_amd64.deb

wget -O python-monotonic_1.5-0ubuntu1_all.deb http://de.archive.ubuntu.com/ubuntu/pool/main/p/python-monotonic/python-monotonic_1.5-0ubuntu1_all.deb
dpkg -i python-monotonic_1.5-0ubuntu1_all.deb
rm      python-monotonic_1.5-0ubuntu1_all.deb

wget -O python-fasteners_0.12.0-3_all.deb http://de.archive.ubuntu.com/ubuntu/pool/main/p/python-fasteners/python-fasteners_0.12.0-3_all.deb
dpkg -i python-fasteners_0.12.0-3_all.deb
rm      python-fasteners_0.12.0-3_all.deb

wget -O duplicity_0.7.18.2-1ubuntu3.1_amd64.deb http://de.archive.ubuntu.com/ubuntu/pool/main/d/duplicity/duplicity_0.7.18.2-1ubuntu3.1_amd64.deb
dpkg -i duplicity_0.7.18.2-1ubuntu3.1_amd64.deb
rm      duplicity_0.7.18.2-1ubuntu3.1_amd64.deb

apt-mark hold duplicity
apt autoremove
