#!/usr/bin/env sh

#
# link config files
#

ln -sf /bootstrap.sh/rootfs/etc/ssh/ssh_config  --target-directory=/etc/ssh/
ln -sf /bootstrap.sh/rootfs/etc/ssh/sshd_config --target-directory=/etc/ssh/



#
# link authorized_keys
#

ln -sf /bootstrap.sh/homefs/.ssh/authorized_keys --target-directory=~/.ssh/
chmod 600 ~/.ssh/authorized_keys



./scripts/ssh-hostkeys
./scripts/ssh-userkeys
./scripts/ssh-moduli
./scripts/ssh-dhtool
