#!/usr/bin/env sh

#
# generate user keys
#

ssh-keygen -N '' -t rsa     -b 4096 -f ~/.ssh/id_rsa_4096
ssh-keygen -N '' -t ecdsa   -b 256  -f ~/.ssh/id_ecdsa_nistp256
ssh-keygen -N '' -t ecdsa   -b 384  -f ~/.ssh/id_ecdsa_nistp384
ssh-keygen -N '' -t ecdsa   -b 521  -f ~/.ssh/id_ecdsa_nistp521
ssh-keygen -N '' -t ed25519         -f ~/.ssh/id_ed25519
