#!/usr/bin/env sh

# https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

fallocate -l 1G /swapfile
chmod 600 /swapfile
mkswap /swapfile

echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
ln -sf /bootstrap.sh/rootfs/etc/sysctl.d/99-quyo-swap.conf --target-directory=/etc/sysctl.d/
