#!/usr/bin/env sh

systemctl disable systemd-resolved.service
service systemd-resolved stop

rm /etc/resolv.conf

echo "nameserver 127.0.0.1" > /etc/resolv.conf
echo "nameserver 165.227.161.223" >> /etc/resolv.conf
echo "nameserver 178.128.253.196" >> /etc/resolv.conf
