#!/usr/bin/env sh

systemctl disable systemd-resolved.service
service systemd-resolved stop

rm /etc/resolv.conf

echo "nameserver 165.227.161.223" >  /etc/resolv.conf
echo "nameserver 178.128.253.196" >> /etc/resolv.conf

sed --in-place 's/^[[:space:]]\([[:space:]]*dns-nameservers\)\(.*\)/#\1\2\n \1 2a03:b0c0:3:d0::dc8:1 2a03:b0c0:2:f0::cb:6001 165.227.161.223 178.128.253.196/' /etc/network/interfaces
sed --in-place 's/^[[:space:]]\([[:space:]]*dns-nameservers\)\(.*\)/#\1\2\n \1 2a03:b0c0:3:d0::dc8:1 2a03:b0c0:2:f0::cb:6001 165.227.161.223 178.128.253.196/' /etc/network/interfaces.d/50-cloud-init.cfg
