#!/usr/bin/env sh

apt install -y unbound dns-root-data

sed --in-place 's/^[[:space:]]\([[:space:]]*dns-nameservers\)\(.*\)/#\1\2\n \1 ::1 127.0.0.1/' /etc/network/interfaces
sed --in-place 's/^[[:space:]]\([[:space:]]*dns-nameservers\)\(.*\)/#\1\2\n \1 ::1 127.0.0.1/' /etc/network/interfaces.d/50-cloud-init.cfg

ln -sf /bootstrap.sh/rootfs/etc/apparmor.d/local/usr.sbin.unbound           /etc/apparmor.d/local/
