#!/usr/bin/env sh

set -e

add-apt-repository ppa:wireguard/wireguard
apt update
apt install wireguard

echo '127.0.0.1' > /etc/resolv.conf

ln -sf /bootstrap.sh/rootfs/etc/unbound/unbound.conf.d/wireguard-listen     /etc/unbound/unbound.conf.d/

ln -sf /bootstrap.sh/rootfs/etc/sysctl.d/99-quyo-wireguard.conf             /etc/sysctl.d/

cat /bootstrap.sh/rootfs/etc/wireguard/wg0.conf                           > /etc/wireguard/wg0.conf
chmod 660 /etc/wireguard/wg0.conf


# FIX /etc/wireguard/wg0.conf


# mkdir ~/wireguard
# cd wireguard
# wg genkey | tee privatekey | wg pubkey > publickey
# chmod 600 *


# wg-quick up wg0
# systemctl enable wg-quick@wg0


# wg set wg0 peer <Client Public Key> allowed-ips 10.10.1.2/32,fc00:10:1::2/128
# wg-quick save wg0
