#!/usr/bin/env sh

set -e

add-apt-repository ppa:wireguard/wireguard
apt update
apt install wireguard qrencode

echo '127.0.0.1' > /etc/resolv.conf

cp /bootstrap.sh/rootfs/etc/unbound/unbound.conf.d/wireguard-listen.conf        /etc/unbound/unbound.conf.d/

ln -sf /bootstrap.sh/rootfs/etc/sysctl.d/99-quyo-wireguard.conf                 /etc/sysctl.d/

cat /bootstrap.sh/rootfs/etc/wireguard/wg0.conf                               > /etc/wireguard/wg0.conf
chmod 660 /etc/wireguard/wg0.conf


# FIX /etc/wireguard/wg0.conf

# wg-quick up wg0
# systemctl enable wg-quick@wg0

# mkdir /etc/wireguard/keys
# chmod 600 /etc/wireguard/keys
# cd /etc/wireguard/keys
# wg genkey | tee server.private.key | wg pubkey > server.public.key
# chmod 600 *



# qrencode -t ansiutf8 < client.conf
# wg set wg0 peer <Client Public Key> allowed-ips 10.10.1.X/32,fc00:10:1::X/128
# wg-quick save wg0
