#!/usr/bin/env sh

# iptables  -A FORWARD -i wg0 -j ACCEPT
# ip6tables -A FORWARD -i wg0 -j ACCEPT

iptables  -t nat -A POSTROUTING -s 10.10.1.0/24   -o ens3 -j MASQUERADE
ip6tables -t nat -A POSTROUTING -s fc00:10:1::/64 -o ens3 -j MASQUERADE
