#!/usr/bin/env sh

# iptables  -D FORWARD -i wg0 -j ACCEPT
# ip6tables -D FORWARD -i wg0 -j ACCEPT

iptables  -t nat -D POSTROUTING -s 10.10.1.0/24   -o ens3 -j MASQUERADE
ip6tables -t nat -D POSTROUTING -s fc00:10:1::/64 -o ens3 -j MASQUERADE
